from flask import Flask, request, jsonify, render_template
from flask_socketio import SocketIO
import os
import logging
from llama_cpp import Llama
import json
from werkzeug.utils import secure_filename
from datetime import datetime

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'Uploads'
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
socketio = SocketIO(app)

# Configure logging
logging.basicConfig(filename='math_discovery_web.log', level=logging.DEBUG, 
                    format='%(asctime)s - %(levelname)s - %(message)s')

# Path to the GGUF file
GGUF_PATH = os.path.join("model", "DeepSeek-Prover-V1.5-RL.Q4_K_S.gguf")

# Prompt templates with examples
PROMPTS = {
    "prove": """You are an expert in unconventional mathematics, specializing in {domain}. Prove the following theorem using {style} reasoning, emphasizing novel approaches such as hyperbolic or non-Euclidean perspectives. Provide a rigorous, step-by-step proof in LaTeX syntax (e.g., \\( \\cosh(c) = \\cosh(a) \\cosh(b) \\)). Include lemmas or conceptual stages for clarity, and highlight deviations from classical logic or geometry.
Theorem: {problem}
Discipline (if relevant): {discipline}
Example (Hyperbolic Geometry):
\\[
\\begin{{align*}}
\\text{{Hyperbolic Pythagorean Theorem:}} \\\\
\\cosh(c) &= \\cosh(a) \\cosh(b) \\\\
\\text{{(By hyperbolic trigonometric identity)}} \\\\
\\sinh^2(x) + 1 &= \\cosh^2(x)
\\end{{align*}}
\\]""",
    "conjecture": """You are a visionary mathematician exploring {domain}. Generate a novel conjecture related to {problem} or {discipline}, using {style} reasoning. Format the conjecture in LaTeX and provide a brief justification, emphasizing connections to hyperbolic or non-Euclidean frameworks if applicable.
Example (Non-Euclidean Geometry):
\\[
\\text{{Conjecture: In a hyperbolic plane, the sum of angles in a triangle is bounded by a function of its area.}}
\\]""",
    "explain": """You are a teacher of unconventional mathematics. Explain the concept or theorem '{problem}' in the context of {domain} using {style} reasoning. Use LaTeX for mathematical expressions and provide intuitive examples or analogies, especially for hyperbolic or non-Euclidean geometries. Relate to {discipline} if provided.
Example (Hyperbolic Geometry):
\\[
\\text{{The Poincaré disk model represents points within a unit disk, with lines as circular arcs perpendicular to the boundary.}}
\\]""",
    "refine": """You are an expert in improving mathematical work. Refine the following output in the context of {domain} using {style} reasoning, emphasizing clarity, rigor, or novelty (e.g., hyperbolic or non-Euclidean insights). Format the result in LaTeX. Previous output: {output}
Example (Hyperbolic Geometry):
\\[
\\text{{Refined: }} \\cosh(d) = \\frac{\\cos(\\alpha) + \\cos(\\beta) \\cos(\\gamma)}{\\sin(\\beta) \\sin(\\gamma)}
\\]""",
    "explore": """You are a creative mathematician specializing in {domain}. Investigate the query or idea '{problem}' using {style} reasoning. Provide insights, hypotheses, or visualizations in LaTeX, emphasizing hyperbolic or non-Euclidean perspectives. Suggest connections to {discipline} or other fields. If no specific problem is provided, explore novel ideas in the domain.
Example (Hyperbolic Geometry):
\\[
\\text{{Exploration: Hyperbolic tilings reveal infinite tessellations, e.g., the order-3 heptagonal tiling with Schläfli symbol \\{7, 3\\}.}}
\\]"""
}

def load_and_run_model(prompt, task, domain, retries=3):
    for attempt in range(retries):
        try:
            if not os.path.exists(GGUF_PATH):
                raise FileNotFoundError(f"Model not found at: {GGUF_PATH}")
            logging.info(f"Attempt {attempt + 1}: Loading model for {task} in {domain}...")
            model = Llama(model_path=GGUF_PATH, n_ctx=4096, verbose=True)
            logging.info(f"Attempt {attempt + 1}: Model loaded.")
            logging.debug(f"Prompt: {prompt}")
            output = model(prompt, max_tokens=4000, temperature=0.7, top_p=0.95)["choices"][0]["text"].strip()
            logging.debug(f"Raw output: {output[:200]}...")
            if not output or output.isspace():
                logging.warning(f"Attempt {attempt + 1}: Model returned empty output.")
                if attempt == retries - 1:
                    return "No output generated by the model after multiple attempts."
                continue
            logging.info(f"Attempt {attempt + 1}: Output generated successfully.")
            return output
        except Exception as e:
            logging.error(f"Attempt {attempt + 1}: Model error: {e}")
            if attempt == retries - 1:
                return f"Error: {str(e)}"
    return "No output generated by the model after multiple attempts."

def save_output(response, task, domain, problem, discipline):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(app.config['UPLOAD_FOLDER'], f"output_{task}_{domain}_{timestamp}.json")
    try:
        output_data = {
            "task": task,
            "domain": domain,
            "problem": problem,
            "discipline": discipline,
            "timestamp": timestamp,
            "response": response
        }
        with open(filename, "w", encoding="utf-8") as f:
            json.dump(output_data, f, indent=2, ensure_ascii=False)
        logging.info(f"Output saved to {filename}")
        return filename
    except Exception as e:
        logging.error(f"Save error: {e}")
        return None

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/process', methods=['POST'])
def process():
    try:
        task = request.form.get('task', 'prove')
        domain = request.form.get('domain', 'hyperbolic_geometry')
        style = request.form.get('style', 'unconventional')
        problem = request.form.get('problem', '')
        discipline = request.form.get('discipline', '')

        logging.info(f"Processing task: {task}, domain: {domain}, style: {style}, problem: {problem}, discipline: {discipline}")

        if task not in PROMPTS:
            return jsonify({'error': f'Invalid task: {task}'}), 400

        if task == 'refine':
            refine_file = request.files.get('refine_file')
            if not refine_file:
                return jsonify({'error': 'No file provided for refinement'}), 400
            filename = secure_filename(refine_file.filename)
            file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            refine_file.save(file_path)
            with open(file_path, 'r', encoding='utf-8') as f:
                previous_output = f.read() if not filename.endswith('.json') else json.load(f).get('response', '')
            prompt = PROMPTS[task].format(output=previous_output, domain=domain, style=style)
        else:
            prompt = PROMPTS[task].format(problem=problem, domain=domain, style=style, discipline=discipline)

        output = load_and_run_model(prompt, task, domain)
        saved_file = save_output(output, task, domain, problem, discipline)
        socketio.emit('new_message', {'task': task, 'domain': domain, 'output': output})
        return jsonify({
            'output': output,
            'saved_file': saved_file
        })
    except Exception as e:
        logging.error(f"Process error: {e}")
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    socketio.run(app, debug=True)